
import { NextResponse } from "next/server";

export async function POST(req) {
  const { title, content } = await req.json();
  // Simulate AI SEO logic
  const optimized = {
    title: `SEO: ${title}`,
    meta: "Enhanced SEO summary generated by AI for your blog.",
    keywords: ["Next.js", "DevDoc’s", "SEO", "WebDev"],
  };
  return NextResponse.json(optimized);
}
