
'use client'
import { useState } from 'react';
import { Wand2 } from 'lucide-react';

export default function AiSummary({ content }) {
    const [summary, setSummary] = useState('');
    const [isLoading, setIsLoading] = useState(false);

    const generateSummary = async () => {
        setIsLoading(true);
        // In a real application, you would make an API call to a service like OpenAI or a custom Firebase Function.
        // For this example, we'll simulate an API call with a timeout.
        setTimeout(() => {
            setSummary('This is a placeholder summary. In a real application, this would be generated by an AI service.');
            setIsLoading(false);
        }, 1500);
    };

    return (
        <div className="my-8 p-6 bg-gray-50 dark:bg-neutral-800 rounded-lg shadow-md">
            <div className="flex items-center justify-between mb-4">
                <h3 className="text-xl font-bold text-gray-900 dark:text-white">AI Summary</h3>
                <button
                    onClick={generateSummary}
                    disabled={isLoading}
                    className="flex items-center space-x-2 px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:bg-indigo-400 dark:focus:ring-offset-neutral-800"
                >
                    <Wand2 size={16} />
                    <span>{isLoading ? 'Generating...' : 'Generate Summary'}</span>
                </button>
            </div>
            {summary && (
                <div className="text-gray-700 dark:text-gray-300">
                    {summary}
                </div>
            )}
        </div>
    );
}
